FeelUnique\Slack\Payload\SearchAllPayloadResponse:
    properties:
        files:
            type: FeelUnique\Slack\Model\FileResult
        messages:
            type: FeelUnique\Slack\Model\MessageResult
