FeelUnique\Slack\Model\Channel:
    properties:
        id:
            type: string
        name:
            type: string
        created:
            type: DateTime<'U'>
        creator:
            type: string
        isArchived:
            type: boolean
        isGeneral:
            type: boolean
        latest:
            type: FeelUnique\Slack\Model\SimpleMessage
        lastRead:
            type: string
        isMember:
            type: boolean
        members:
            type: array<string>
        topic:
            type: FeelUnique\Slack\Model\Customizable
        purpose:
            type: FeelUnique\Slack\Model\Customizable
