FeelUnique\Slack\Model\Group:
    properties:
        id:
            type: string
        name:
            type: string
        created:
            type: DateTime<'U'>
        creator:
            type: string
        isArchived:
            type: boolean
        members:
            type: array<string>
        topic:
            type: FeelUnique\Slack\Model\Customizable
        purpose:
            type: FeelUnique\Slack\Model\Customizable
        isGroup:
            type: boolean
        lastRead:
            type: string
        latest:
            type: FeelUnique\Slack\Model\Message
        unreadCount:
            type: integer
        unreadCountDisplay:
            type: integer
