FeelUnique\Slack\Payload\GroupsHistoryPayloadResponse:
    properties:
        latest:
            type: string
        messages:
            type: array<FeelUnique\Slack\Model\SimpleMessage>
        hasMore:
            type: boolean
